"""
Run migrated jobs without an orchestration service.
Auto-generated by the migration tool.
"""
from __future__ import annotations

import argparse
import importlib.util
import logging
import os
import sys
import time
from pathlib import Path
from types import ModuleType


JOBS = {
    'XmlToJson_demo': 'XmlToJson_demo',
    'JsonToXml_demo': 'JsonToXml_demo'
}
logger = logging.getLogger("migrated_runtime")


def _load_dotenv(path: Path) -> None:
    """Load simple KEY=VALUE lines while preserving environment overrides."""
    if not path.exists():
        return
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export "):].strip()
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
            value = value[1:-1]
        if key:
            os.environ.setdefault(key, value)


def _load_module(root: Path, job_name: str) -> ModuleType:
    job_file = root / "jobs" / job_name / "main.py"
    if not job_file.exists():
        raise FileNotFoundError(f"Missing generated job module: {job_file}")
    spec = importlib.util.spec_from_file_location(
        f"migrated_job_{JOBS[job_name]}",
        job_file,
    )
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load generated job module: {job_file}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _run_job(root: Path, job_name: str) -> None:
    _load_dotenv(root / "jobs" / job_name / ".env")
    module = _load_module(root, job_name)
    entrypoint_name = JOBS[job_name]
    entrypoint = getattr(module, entrypoint_name, None)
    if not callable(entrypoint):
        candidates = [
            value
            for name, value in vars(module).items()
            if not name.startswith("_")
            and callable(value)
            and getattr(value, "__module__", None) == module.__name__
        ]
        if len(candidates) != 1:
            raise RuntimeError(
                f"Generated job {job_name!r} has no callable entrypoint {entrypoint_name!r}"
            )
        entrypoint = candidates[0]
    started = time.monotonic()
    logger.info("Starting job %s", job_name)
    entrypoint()
    logger.info("Finished job %s in %.2fs", job_name, time.monotonic() - started)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Run migrated jobs.")
    parser.add_argument(
        "--job",
        dest="jobs",
        action="append",
        choices=tuple(JOBS),
        help="Run only this job. Repeat to run multiple jobs in order.",
    )
    parser.add_argument("--list", action="store_true", help="List runnable jobs and exit.")
    args = parser.parse_args(argv)

    if args.list:
        for name in JOBS:
            print(name)
        return 0

    logging.basicConfig(
        level=os.environ.get("LOG_LEVEL", "INFO").upper(),
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
    )
    root = Path(__file__).resolve().parent
    _load_dotenv(root / ".env")

    selected_jobs = args.jobs or list(JOBS)
    failed = []
    for job_name in selected_jobs:
        try:
            _run_job(root, job_name)
        except Exception:
            logger.exception("Job %s failed", job_name)
            failed.append(job_name)

    if failed:
        logger.error("Runtime failed for %d job(s): %s", len(failed), ", ".join(failed))
        return 1
    logger.info("Runtime completed %d job(s).", len(selected_jobs))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
